import './styles.css'
import {createRoot} from 'react-dom/client'
import {createRootRoute,createRoute,createRouter,RouterProvider} from '@tanstack/react-router'
import {QueryClientProvider,useQuery} from '@tanstack/react-query'
import {useForm} from '@tanstack/react-form'
import {createRueQueryClient,createRueTrpcClient} from '@multiterm/rue-trpc/client'
import {Badge,Button,ButtonLink,Card,CardContent,CardDescription,CardHeader,CardTitle,Input,ThemeControls,ThemeProvider} from '@multiterm/rue-ui'
const trpc=createRueTrpcClient({baseUrl:import.meta.env.VITE_RUE_API_URL??location.origin})
function Site(){const health=useQuery({queryKey:['health'],queryFn:()=>trpc.health.query(),retry:false});const form=useForm({defaultValues:{email:''},onSubmit:async()=>form.reset()});return <><header className="border-b border-border bg-background/60 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6"><a href="/" className="font-display text-2xl font-black">Rue</a><nav className="flex items-center gap-5"><a className="hidden text-sm font-semibold text-muted hover:text-foreground sm:block" href="#surfaces">Surfaces</a><ButtonLink variant="ghost" href={import.meta.env.VITE_RUE_DOCS_URL??'https://docs.rue.multiterm.dev'}>Docs</ButtonLink><ThemeControls/><ButtonLink href={import.meta.env.VITE_RUE_APP_URL??'https://app.rue.multiterm.dev'}>Open Rue</ButtonLink></nav></div></header><main className="mx-auto max-w-7xl px-6 py-24"><Badge>{health.isSuccess?'Rue network online':'MULTISURFACE AI'}</Badge><h1 className="mt-8 max-w-6xl font-display text-[clamp(4rem,11vw,9rem)] font-black leading-[.82] tracking-[-.07em]">Think once.<br/><span className="text-primary">Work everywhere.</span></h1><p className="mt-9 max-w-3xl text-[clamp(1.25rem,2.5vw,2rem)] leading-tight text-muted">Rue carries your sessions from terminal to web, native mobile, and desktop—secured by Keyname.</p><div className="mt-10 flex flex-wrap items-center gap-5"><ButtonLink size="lg" href={import.meta.env.VITE_RUE_APP_URL??'https://app.rue.multiterm.dev'}>Start with Keyname</ButtonLink><ButtonLink size="lg" variant="outline" href="https://github.com/multiterm/rue">View source →</ButtonLink></div><section id="surfaces" className="mt-28 grid gap-5 border-t border-border pt-12 md:grid-cols-2 xl:grid-cols-4">{[['Web','TanStack-powered React client.'],['Mobile','Native Expo app on Runway.'],['Desktop','Focused Electron workspace.'],['Terminal','Keyboard-first TUI.']].map(([title,description])=><Card key={title}><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader></Card>)}</section><Card className="mt-24 overflow-hidden"><CardContent className="grid gap-8 p-8 md:grid-cols-[1fr_420px] md:items-center"><div><h2 className="font-display text-4xl font-black">Follow the build.</h2><p className="mt-3 text-muted">Get release notes for the shared GDS, SDK, and applications.</p></div><form onSubmit={e=>{e.preventDefault();void form.handleSubmit()}} className="flex gap-2"><form.Field name="email">{field=><Input type="email" required aria-label="Email" placeholder="you@example.com" value={field.state.value} onChange={e=>field.handleChange(e.target.value)}/>}</form.Field><Button type="submit">Subscribe</Button></form></CardContent></Card></main></>}
const root=createRootRoute();const index=createRoute({getParentRoute:()=>root,path:'/',component:Site});const router=createRouter({routeTree:root.addChildren([index])});declare module '@tanstack/react-router'{interface Register{router:typeof router}}const queryClient=createRueQueryClient();createRoot(document.getElementById('root')!).render(<ThemeProvider><QueryClientProvider client={queryClient}><RouterProvider router={router}/></QueryClientProvider></ThemeProvider>)
