import {useEffect,useState} from 'react'
import {Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native'
import Constants from 'expo-constants'
import * as AuthSession from 'expo-auth-session'
import * as SecureStore from 'expo-secure-store'
import {rueNativeThemes} from '@multiterm/rue-gds'
const keynameApiUrl=String(Constants.expoConfig?.extra?.keynameApiUrl??'https://api.keyname.dev');const clientId=String(Constants.expoConfig?.extra?.keynameClientId??'');const rueApiUrl=String(Constants.expoConfig?.extra?.rueApiUrl??'https://api.rue.multiterm.dev');const redirectUri=AuthSession.makeRedirectUri({scheme:'rue',path:'auth/callback'});const discovery={authorizationEndpoint:`${keynameApiUrl}/authorize`,tokenEndpoint:`${keynameApiUrl}/v1/code/exchange`};const TOKEN_KEY='rue.keyname.tokens'
interface Session{id:string;title:string}
export default function Home(){const[request,response,promptAsync]=AuthSession.useAuthRequest({clientId,redirectUri,scopes:['openid','profile','email'],usePKCE:true},discovery);const[token,setToken]=useState<string>();const[sessions,setSessions]=useState<Session[]>([]);const[error,setError]=useState('');useEffect(()=>{SecureStore.getItemAsync(TOKEN_KEY).then((stored)=>{if(!stored)return;try{const parsed=JSON.parse(stored) as{accessToken?:string};setToken(parsed.accessToken)}catch{void SecureStore.deleteItemAsync(TOKEN_KEY)}})},[]);useEffect(()=>{if(response?.type!=='success'||!request?.codeVerifier)return;setError('');AuthSession.exchangeCodeAsync({clientId,code:response.params.code,redirectUri,extraParams:{code_verifier:request.codeVerifier}},discovery).then(async(tokens)=>{await SecureStore.setItemAsync(TOKEN_KEY,JSON.stringify(tokens));setToken(tokens.accessToken)}).catch((cause)=>setError(cause instanceof Error?cause.message:'Sign-in failed'))},[request,response]);useEffect(()=>{if(!token)return;fetch(`${rueApiUrl.replace(/\/$/,'')}/session`,{headers:{authorization:`Bearer ${token}`}}).then(async(result)=>{if(!result.ok)throw new Error(`Rue API returned ${result.status}`);setSessions(await result.json() as Session[])}).catch((cause)=>setError(cause instanceof Error?cause.message:'Could not load sessions'))},[token]);const signOut=async()=>{await SecureStore.deleteItemAsync(TOKEN_KEY);setToken(undefined);setSessions([])};return <SafeAreaView style={styles.root}><ScrollView contentContainerStyle={styles.content}><View><Text style={styles.mark}>RUE</Text><Text style={styles.title}>{token?'Your sessions.':'Your workspace, in motion.'}</Text><Text style={styles.copy}>{token?'Continue a conversation from any Rue surface.':'Continue sessions from web, desktop, or terminal.'}</Text></View>{token?<View style={styles.sessions}>{sessions.length?sessions.map((session)=><View key={session.id} style={styles.session}><Text style={styles.sessionText}>{session.title||'Untitled session'}</Text></View>):<Text style={styles.copy}>No sessions yet.</Text>}<Pressable style={styles.secondaryButton} onPress={()=>void signOut()}><Text style={styles.buttonText}>Sign out</Text></Pressable></View>:<Pressable disabled={!request||!clientId} style={[styles.button,(!request||!clientId)&&styles.disabled]} onPress={()=>void promptAsync()}><Text style={styles.buttonText}>Continue with Keyname</Text></Pressable>}{error?<Text accessibilityRole="alert" style={styles.error}>{error}</Text>:null}</ScrollView></SafeAreaView>}
const colors=rueNativeThemes.dark
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},content:{flexGrow:1,justifyContent:'space-between',padding:32},mark:{color:colors.primary,fontWeight:'800',letterSpacing:5,marginTop:40},title:{color:colors.text,fontSize:56,fontWeight:'800',lineHeight:58,marginTop:80},copy:{color:colors.muted,fontSize:18,lineHeight:27,marginTop:20},button:{backgroundColor:colors.primary,padding:18,borderRadius:14,alignItems:'center',marginBottom:24},secondaryButton:{backgroundColor:colors.surface,padding:18,borderRadius:14,alignItems:'center',marginTop:20},disabled:{opacity:.5},buttonText:{color:colors.background,fontWeight:'800',fontSize:16},sessions:{marginTop:40,gap:12},session:{backgroundColor:colors.surface,padding:18,borderRadius:12},sessionText:{color:colors.text,fontWeight:'700'},error:{color:'#ff8b8b',marginTop:12}})
