export type RueService='api'|'webapp'|'site'|'docs'
export interface RueAppEnv { MODE?:string; SANDBLOCKS_RUNTIME?:string; SANDBLOCKS_SERVICE_API_URL?:string; SANDBLOCKS_SERVICE_WEBAPP_URL?:string; SANDBLOCKS_SERVICE_SITE_URL?:string; SANDBLOCKS_SERVICE_DOCS_URL?:string; SANDBLOCKS_STABLE_SERVICE_API_URL?:string; SANDBLOCKS_STABLE_SERVICE_WEBAPP_URL?:string; SANDBLOCKS_STABLE_SERVICE_SITE_URL?:string; SANDBLOCKS_STABLE_SERVICE_DOCS_URL?:string; VITE_RUE_API_URL?:string; VITE_RUE_APP_URL?:string; VITE_RUE_SITE_URL?:string; VITE_RUE_DOCS_URL?:string; VITE_KEYNAME_API_URL?:string }
export interface RueAppUrls {api:string;webapp:string;site:string;docs:string;login:string;github:string;keynameApi:string}
const ports={api:4097,webapp:5173,site:5174,docs:5175} as const
const envKeys={api:'SANDBLOCKS_SERVICE_API_URL',webapp:'SANDBLOCKS_SERVICE_WEBAPP_URL',site:'SANDBLOCKS_SERVICE_SITE_URL',docs:'SANDBLOCKS_SERVICE_DOCS_URL'} as const
const stableKeys={api:'SANDBLOCKS_STABLE_SERVICE_API_URL',webapp:'SANDBLOCKS_STABLE_SERVICE_WEBAPP_URL',site:'SANDBLOCKS_STABLE_SERVICE_SITE_URL',docs:'SANDBLOCKS_STABLE_SERVICE_DOCS_URL'} as const
const explicitKeys={api:'VITE_RUE_API_URL',webapp:'VITE_RUE_APP_URL',site:'VITE_RUE_SITE_URL',docs:'VITE_RUE_DOCS_URL'} as const
const clean=(value?:string)=>{if(!value)return '';try{return new URL(value).toString().replace(/\/$/,'')}catch{return ''}}
export function createRueAppConfig(env:RueAppEnv,service:RueService,currentOrigin?:string){const runtime=env.SANDBLOCKS_RUNTIME??env.MODE??'local';const local=runtime==='development'||runtime==='dev'||runtime==='local'||runtime==='test';const sandblocks=Object.values(envKeys).some(key=>Boolean(env[key]));const fallback:Record<RueService,string>=local?{api:`http://localhost:${ports.api}`,webapp:`http://localhost:${ports.webapp}`,site:`http://localhost:${ports.site}`,docs:`http://localhost:${ports.docs}`}:{api:'https://api.rue.multiterm.dev',webapp:'https://app.rue.multiterm.dev',site:'https://rue.multiterm.dev',docs:'https://docs.rue.multiterm.dev'};const url=(name:RueService)=>clean(env[envKeys[name]])||clean(env[stableKeys[name]])||clean(env[explicitKeys[name]])||(name===service?clean(currentOrigin):'')||fallback[name];const urls={api:url('api'),webapp:url('webapp'),site:url('site'),docs:url('docs')};return {runtime,service,sandbox:sandblocks,urls:{...urls,login:`${urls.webapp}/login`,github:'https://github.com/multiterm/rue',keynameApi:clean(env.VITE_KEYNAME_API_URL)||'https://api.keyname.dev'} satisfies RueAppUrls}}
export function safeRedirect(value:string|undefined,fallback='/'){if(!value||!value.startsWith('/')||value.startsWith('//'))return fallback;return value}
