import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest'
import {createApp} from '../../src/server/index.js'
import {Bus} from '../../src/bus/index.js'
import {ConfigSchema} from '../../src/config/index.js'
import {openDatabase} from '../../src/storage/index.js'
import type {ServerContext} from '../../src/server/index.js'
const device=(id:string)=>({deviceId:id,name:`Device ${id}`,platform:'web'})
function context():ServerContext{return{db:openDatabase(':memory:'),config:ConfigSchema.parse({}),bus:new Bus()}}
describe('device pairing and sync',()=>{let ctx:ServerContext;beforeEach(()=>{ctx=context()});afterEach(()=>ctx.db.close())
it('pairs one device once and supports revocation',async()=>{const app=createApp({ctx});const created=await app.request('/pairing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(device('dev_source'))}).then(r=>r.json() as Promise<{id:string;token:string;code:string;expiresAt:number}>);expect(created.token).not.toContain(created.code);expect(created.code).toMatch(/^\d{8}$/);const claimed=await app.request('/pairing/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...device('dev_mobile'),token:created.token})});expect(claimed.status).toBe(200);expect((await app.request('/device').then(r=>r.json() as Promise<unknown[]>))).toHaveLength(2);expect((await app.request(`/pairing/${created.id}`).then(r=>r.json() as Promise<{claimedDeviceId:string}>)).claimedDeviceId).toBe('dev_mobile');expect((await app.request('/pairing/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...device('dev_other'),code:created.code})})).status).toBe(410);expect(await app.request('/device/dev_mobile',{method:'DELETE'}).then(r=>r.json())).toEqual({revoked:true})})
it('rejects expired pairings',async()=>{const app=createApp({ctx});const created=await app.request('/pairing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(device('dev_source'))}).then(r=>r.json() as Promise<{id:string;token:string}>);ctx.db.prepare('UPDATE device_pairings SET expires_at=? WHERE id=?').run(Date.now()-1,created.id);expect((await app.request('/pairing/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...device('dev_mobile'),token:created.token})})).status).toBe(410)})
it('uses optimistic versions for synced preferences',async()=>{const app=createApp({ctx});const first=await app.request('/sync/preferences/theme',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({value:'Midnight',expectedVersion:0})});expect(await first.json()).toMatchObject({key:'theme',value:'Midnight',version:1});const conflict=await app.request('/sync/preferences/theme',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({value:'Paper',expectedVersion:0})});expect(conflict.status).toBe(409);expect(await app.request('/sync/preferences').then(r=>r.json())).toEqual([expect.objectContaining({key:'theme',value:'Midnight',version:1})])})
it('does not allow another Keyname subject to redeem a token',async()=>{ctx.config.keyname.enabled=true;const verify=vi.spyOn(globalThis,'fetch').mockImplementation(async(_url,init)=>{const token=(JSON.parse(String(init?.body)) as{token:string}).token;return Response.json({token:{subject:token,principalType:'user'}})});const app=createApp({ctx});const created=await app.request('/pairing',{method:'POST',headers:{authorization:'Bearer owner_a','content-type':'application/json'},body:JSON.stringify(device('dev_source'))}).then(r=>r.json() as Promise<{token:string}>);const response=await app.request('/pairing/redeem',{method:'POST',headers:{authorization:'Bearer owner_b','content-type':'application/json'},body:JSON.stringify({...device('dev_mobile'),token:created.token})});expect(response.status).toBe(410);verify.mockRestore()})})
