import {useForm} from '@tanstack/react-form'
import {Link,Outlet,useLocation} from '@tanstack/react-router'
import {useQuery} from '@tanstack/react-query'
import {Input,ThemeControls,cn} from '@multiterm/rue-ui'
import {headings,type Heading} from './MarkdownPage'
import {pages,trpc} from '../router'
import {app} from '../app'
const nav=[{group:'Start',items:[['/','Introduction'],['/authentication','Authentication']]},{group:'Build',items:[['/design-system','Design system'],['/deployment','Deployment']]}] as const
export function DocsLayout(){const location=useLocation();const current=pages[location.pathname as keyof typeof pages]??pages['/'];const pageHeadings:Heading[]=headings(current);const form=useForm({defaultValues:{query:''}});const status=useQuery({queryKey:['rue','health'],queryFn:()=>trpc.health.query(),retry:false});return <><header className="sticky top-0 z-20 border-b border-border bg-background/80 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-7"><div className="flex items-center gap-4"><Link to="/" className="font-display text-xl font-black tracking-tight">Rue <span className="text-muted">Docs</span></Link><a href={app.urls.site} className="text-xs font-semibold text-muted hover:text-foreground">Home</a></div><div className="flex items-center gap-3"><span className={cn('hidden text-xs sm:block',status.isSuccess?'text-success':'text-subtle')}>{status.isSuccess?'API connected':'API offline'}</span><ThemeControls/><a href={app.urls.login} className="hidden text-xs font-bold text-primary sm:block">Open Rue</a></div></div></header><div className="mx-auto grid max-w-[1440px] grid-cols-[250px_minmax(0,820px)_190px] items-start gap-10 px-7 py-10 max-[1100px]:grid-cols-[230px_minmax(0,1fr)] max-[780px]:block"><aside className="sticky top-24 max-h-[calc(100vh-7rem)] overflow-y-auto max-[780px]:static max-[780px]:mb-8"><form.Field name="query">{field=><Input type="search" aria-label="Search docs" placeholder="Search docs…" value={field.state.value} onChange={e=>field.handleChange(e.target.value)} className="mb-6"/>}</form.Field><form.Subscribe selector={state=>state.values.query}>{query=><nav className="grid gap-6">{nav.map(group=>{const items=group.items.filter(([,label])=>label.toLowerCase().includes(query.toLowerCase()));return items.length?<section key={group.group}><h2 className="mb-2 text-xs font-bold uppercase tracking-[.14em] text-subtle">{group.group}</h2><div className="grid gap-1">{items.map(([to,label])=><Link key={to} to={to} activeOptions={{exact:true}} className="rounded-md px-3 py-2 text-sm font-semibold text-muted hover:bg-surface hover:text-foreground [&.active]:bg-surface [&.active]:text-foreground">{label}</Link>)}</div></section>:null})}</nav>}</form.Subscribe></aside><main className="min-w-0"><Outlet/></main><aside className="sticky top-24 max-h-[calc(100vh-7rem)] overflow-y-auto max-[1100px]:hidden"><h2 className="mb-3 text-xs font-bold uppercase tracking-[.14em] text-subtle">On this page</h2><nav className="grid gap-1">{pageHeadings.map(heading=><a key={heading.id} href={`#${heading.id}`} className={cn('border-l border-border py-1 text-xs text-muted hover:text-foreground',heading.level===3?'pl-6':'pl-3')}>{heading.label}</a>)}</nav></aside></div></>}
