import * as React from 'react'
import {cva,type VariantProps} from 'class-variance-authority'
import {cn} from '../_utils/cn.js'
export type ButtonMode='Primary'|'Secondary'|'Warning'|'Danger'|'Success'
export const buttonVariants=cva('pointer-events-auto relative inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-md border font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-control/30 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50',{variants:{variant:{primary:'border-transparent bg-control text-control-foreground hover:brightness-110 active:brightness-95',secondary:'border-transparent bg-foreground text-background hover:bg-muted active:brightness-90',outline:'border-border-strong bg-transparent text-foreground hover:border-control hover:bg-surface-2 active:bg-surface',ghost:'border-transparent bg-transparent text-muted hover:bg-surface hover:text-foreground active:bg-surface-2',destructive:'border-transparent bg-danger text-white hover:brightness-110'},size:{mini:'min-h-6 px-2 py-0.5 text-[11px]',sm:'min-h-8 px-2.5 py-1 text-xs',regular:'min-h-9 px-4 py-2 text-sm',default:'min-h-9 px-4 py-2 text-sm',lg:'min-h-10 px-6 py-2.5 text-sm',icon:'size-9 p-0'}},defaultVariants:{variant:'primary',size:'regular'}})
export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement>,VariantProps<typeof buttonVariants>{mode?:ButtonMode;isLoading?:boolean}
export const Button=React.forwardRef<HTMLButtonElement,ButtonProps>(({className,variant,size,mode='Primary',isLoading=false,children,disabled,...props},ref)=><span className="contents" data-mode={variant==='destructive'?'Danger':mode}><button ref={ref} className={cn(buttonVariants({variant,size}),className)} disabled={disabled||isLoading} aria-busy={isLoading||undefined} {...props}>{isLoading?<><span className="size-4 animate-spin rounded-full border-2 border-current border-r-transparent"/>Loading…</>:children}</button></span>)
Button.displayName='Button'
export function ButtonLink({className,variant,size,mode='Primary',children,...props}:React.AnchorHTMLAttributes<HTMLAnchorElement>&VariantProps<typeof buttonVariants>&{mode?:ButtonMode}){return <span className="contents" data-mode={mode}><a className={cn(buttonVariants({variant,size}),className)} {...props}>{children}</a></span>}
