use_default_settings: true

general:
  instance_name: "Rue"
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  secret_key: "change-this-to-a-long-random-string-in-production"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true

engines:
  - name: google
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: wikipedia
    disabled: false
