import {expect,test} from '@playwright/test'
const tokenRecord={token:'keyname-test-token',record:{subject:'usr_test',userEmail:'rue@example.com',principalType:'user'}}
test.beforeEach(async({page})=>{
  const sessions:Array<Record<string,unknown>>=[];const messages=new Map<string,Array<Record<string,unknown>>>();const parts=new Map<string,Array<Record<string,unknown>>>()
  await page.route('https://api.keyname.dev/auth.js',route=>route.fulfill({status:200,contentType:'text/javascript',body:`(()=>{let user=null;let listeners=[];window.Keyname={ready:Promise.resolve(null),currentUser:async()=>user,getAccessToken:async()=>user?'keyname-test-token':null,signIn:async({mode})=>{window.__keynameMode=mode;if(mode==='modal'){user=${JSON.stringify(tokenRecord.record)};listeners.forEach(fn=>fn({authenticated:true,record:user}));return ${JSON.stringify(tokenRecord)}}return null},signOut:async()=>{user=null;listeners.forEach(fn=>fn({authenticated:false,record:null}))},closeModal(){},onAuthChange(fn){listeners.push(fn);return()=>listeners=listeners.filter(x=>x!==fn)},startSessionPolling(){return 0}}})()`}))
  await page.route('http://localhost:4097/**',async route=>{const request=route.request();const url=new URL(request.url());const path=url.pathname;const json=(body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});if(path==='/session'&&request.method()==='GET')return json(sessions);if(path==='/session'&&request.method()==='POST'){const input=request.postDataJSON();const id=`ses_${sessions.length+1}`;const session={id,title:input.title??'',agent:null,provider:'openrouter',model:'test',directory:null,scopes:[],parentId:null,ownerSubject:'usr_test',createdAt:Date.now(),updatedAt:Date.now(),meta:{}};sessions.unshift(session);messages.set(id,[]);parts.set(id,[]);return json(session)}const messageMatch=path.match(/^\/session\/([^/]+)\/message$/);if(messageMatch&&request.method()==='POST'){const id=messageMatch[1];const input=request.postDataJSON();const userId='msg_user',assistantId='msg_assistant';messages.set(id,[{id:userId,sessionId:id,role:'user',time:Date.now(),provider:null,model:null,agent:null,meta:{},seq:0},{id:assistantId,sessionId:id,role:'assistant',time:Date.now(),provider:'openrouter',model:'test',agent:null,meta:{},seq:1}]);parts.set(id,[{id:'txt_user',sessionId:id,messageId:userId,type:'text',seq:0,payload:{text:input.text}},{id:'txt_assistant',sessionId:id,messageId:assistantId,type:'text',seq:0,payload:{text:'Hello from Rue'}}]);return json({userMessageId:userId,assistantMessageId:assistantId,text:'Hello from Rue',stopReason:'completed'})}const messagesMatch=path.match(/^\/session\/([^/]+)\/messages$/);if(messagesMatch)return json(messages.get(messagesMatch[1])??[]);const partsMatch=path.match(/^\/session\/([^/]+)\/parts$/);if(partsMatch)return json(parts.get(partsMatch[1])??[]);return json({error:'not_found'},404)})
})
test('anonymous users receive the Keyname login page',async({page})=>{await page.goto('/');await expect(page).toHaveURL(/\/login\?redirect=%2F/);await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();await expect(page.getByRole('button',{name:/Sign in with Keyname/})).toBeEnabled()})
test('Keyname modal signs in and sign-out returns to login',async({page})=>{await page.goto('/login');await page.getByRole('button',{name:/Sign in with Keyname/}).click();await expect(page).toHaveURL('http://127.0.0.1:5173/');await expect(page.getByText('rue@example.com')).toBeVisible();await expect(page.getByRole('heading',{name:/One assistant/})).toBeVisible();await page.getByRole('button',{name:'Sign out'}).click();await expect(page).toHaveURL(/\/login/)})
test('workspace creates a session and completes a message round trip',async({page})=>{await page.goto('/login');await page.getByRole('button',{name:/Sign in with Keyname/}).click();const message=page.getByLabel('Message');await message.fill('Hello Rue');await page.getByRole('button',{name:'Send'}).click();await expect(message).toHaveValue('');await expect(page.getByText('Agent response completed.')).toBeVisible();await expect(page.getByText('Hello from Rue')).toBeVisible()})
test('redirect login mode is available',async({page})=>{await page.goto('/login');await page.getByRole('button',{name:'Continue in a new page'}).click();await expect.poll(()=>page.evaluate(()=>window.__keynameMode)).toBe('redirect')})
declare global{interface Window{__keynameMode?:string}}
