import {createContext,useCallback,useContext,useEffect,useState,type ReactNode} from 'react'
import {loadKeyname,type KeynameBrowserClient,type KeynameUser} from '@multiterm/rue-auth'
import {app} from './app'
type Status='loading'|'authenticated'|'anonymous'|'error'
interface AuthState{status:Status;user:KeynameUser|null;error:string;signIn(mode?:'modal'|'redirect'):Promise<void>;signOut():Promise<void>}
const Context=createContext<AuthState|null>(null)
let activeClient:KeynameBrowserClient|undefined
export async function keynameAccessToken(){return activeClient?.getAccessToken({minValidityMs:60_000})??null}
export function KeynameProvider({children}:{children:ReactNode}){const[status,setStatus]=useState<Status>('loading');const[user,setUser]=useState<KeynameUser|null>(null);const[error,setError]=useState('');const sync=useCallback(async(client:KeynameBrowserClient)=>{const next=await client.currentUser();setUser(next);setStatus(next?'authenticated':'anonymous')},[]);useEffect(()=>{let unsubscribe=()=>{};let disposed=false;loadKeyname(app.urls.keynameApi).then(async client=>{if(disposed)return;activeClient=client;await client.ready;await sync(client);unsubscribe=client.onAuthChange(()=>void sync(client))}).catch(cause=>{if(!disposed){setError(cause instanceof Error?cause.message:'Could not connect to Keyname');setStatus('error')}});return()=>{disposed=true;unsubscribe()}},[sync]);const signIn=async(mode:'modal'|'redirect'='modal')=>{setError('');const client=activeClient??await loadKeyname(app.urls.keynameApi);activeClient=client;await client.ready;const tokens=await client.signIn({mode,callbackUri:`${app.urls.webapp}/login`});if(mode==='modal'&&tokens)await sync(client)};const signOut=async()=>{if(activeClient)await activeClient.signOut();setUser(null);setStatus('anonymous')};return <Context.Provider value={{status,user,error,signIn,signOut}}>{children}</Context.Provider>}
export function useKeyname(){const value=useContext(Context);if(!value)throw new Error('useKeyname must be used inside KeynameProvider');return value}
