import './styles.css'
import {StrictMode,useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {createRootRoute,createRoute,createRouter,Link,Outlet,RouterProvider,useNavigate} from '@tanstack/react-router'
import {QueryClientProvider,useQuery} from '@tanstack/react-query'
import {useForm} from '@tanstack/react-form'
import {safeRedirect} from '@multiterm/rue-config/app'
import {createRueQueryClient,createRueTrpcClient} from '@multiterm/rue-trpc/client'
import {Badge,Button,ButtonLink,Card,CardContent,CardDescription,CardHeader,CardTitle,Input,ThemeControls,ThemeProvider} from '@multiterm/rue-ui'
import {app} from './app'
import {KeynameProvider,keynameAccessToken,useKeyname} from './auth'
const trpc=createRueTrpcClient({baseUrl:app.urls.api,token:async()=>await keynameAccessToken()??undefined})
function KeyIcon(){return <svg aria-hidden="true" viewBox="0 0 24 24" className="size-4 fill-none stroke-current" strokeWidth="2"><circle cx="8" cy="15" r="4"/><path d="m11 12 8-8m-2 2 2 2m-5 1 2 2"/></svg>}
function Login(){const{status,user,error:authError,signIn}=useKeyname();const navigate=useNavigate();const{redirect}=loginRoute.useSearch();const[error,setError]=useState('');useEffect(()=>{if(status==='authenticated'&&user)void navigate({to:safeRedirect(redirect),replace:true})},[navigate,redirect,status,user]);const start=async(mode:'modal'|'redirect')=>{setError('');try{await signIn(mode)}catch(cause){setError(cause instanceof Error?cause.message:'Keyname sign-in failed')}};return <main className="grid min-h-dvh place-items-center px-5 py-12"><Card className="w-full max-w-md"><CardHeader className="text-center"><Link to="/" className="mx-auto mb-4 font-display text-3xl font-black text-primary">Rue</Link><CardTitle>Welcome back</CardTitle><CardDescription>Sign in with Keyname to continue to your Rue workspace.</CardDescription></CardHeader><CardContent className="grid gap-4"><Button size="lg" variant="secondary" className="w-full" isLoading={status==='loading'} disabled={status==='loading'} onClick={()=>void start('modal')}><KeyIcon/>Sign in with Keyname</Button><div className="flex items-center gap-3 text-xs font-semibold text-subtle"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div><Button size="lg" variant="outline" className="w-full" onClick={()=>void start('redirect')}>Continue in a new page</Button>{(error||authError)&&<p role="alert" className="m-0 rounded-md border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error||authError}</p>}<p className="m-0 text-center text-xs leading-5 text-subtle">Keyname manages passwords, passkeys, connected providers, MFA, token refresh, and session revocation.</p><div className="flex justify-center gap-4 text-xs text-muted"><a href={app.urls.site}>Rue home</a><a href={app.urls.docs}>Documentation</a></div></CardContent></Card></main>}
function Workspace(){const auth=useKeyname();const navigate=useNavigate();const[message,setMessage]=useState('');useEffect(()=>{if(auth.status==='anonymous'||auth.status==='error')void navigate({to:'/login',search:{redirect:'/'},replace:true})},[auth.status,navigate]);const sessions=useQuery({queryKey:['sessions'],queryFn:()=>trpc.sessions.query(),retry:false,enabled:auth.status==='authenticated'});const form=useForm({defaultValues:{message:''},onSubmit:async({value})=>{if(!value.message.trim())return;setMessage('Agent streaming is connected through the Rue session API.');form.reset()}});if(auth.status==='loading')return <div role="status" className="grid min-h-dvh place-items-center text-sm text-muted">Checking your Keyname session…</div>;return <main className="grid min-h-dvh grid-cols-[250px_1fr] max-md:grid-cols-1"><aside className="border-r border-border bg-background/60 p-7 backdrop-blur-xl max-md:hidden"><div className="font-display text-3xl font-black text-primary">Rue</div><Button className="mt-8 w-full">New session</Button><nav className="mt-8 grid gap-2 text-sm text-muted">{sessions.data?.map(session=><button className="rounded-md px-3 py-2 text-left hover:bg-surface" key={session.id}>{session.title||'Untitled session'}</button>)??<span>{sessions.isLoading?'Loading sessions…':'No sessions yet'}</span>}</nav></aside><section className="grid min-w-0 grid-rows-[auto_1fr_auto] gap-6 p-6"><header className="flex items-center justify-between"><Badge>{auth.user?.userEmail??'Keyname session'}</Badge><div className="flex items-center gap-3"><ButtonLink variant="ghost" href={app.urls.docs}>Docs</ButtonLink><ThemeControls/><Button variant="secondary" onClick={()=>void auth.signOut()}>Sign out</Button></div></header><article className="m-auto max-w-4xl"><h1 className="font-display text-[clamp(3.5rem,8vw,7.5rem)] font-black leading-[.86] tracking-[-.06em]">One assistant.<br/><span className="text-primary">Every surface.</span></h1><p className="mt-7 max-w-2xl text-xl leading-8 text-muted">Web, mobile, desktop, and terminal sessions powered by TanStack, tRPC, Drizzle, and Keyname.</p>{message&&<p className="mt-5 text-sm text-warning">{message}</p>}</article><form onSubmit={e=>{e.preventDefault();e.stopPropagation();void form.handleSubmit()}} className="mx-auto flex w-full max-w-4xl gap-3"><form.Field name="message">{field=><Input aria-label="Message" placeholder="Ask Rue anything…" value={field.state.value} onChange={e=>field.handleChange(e.target.value)}/>}</form.Field><Button type="submit">Send</Button></form></section></main>}
const rootRoute=createRootRoute({component:Outlet});const indexRoute=createRoute({getParentRoute:()=>rootRoute,path:'/',component:Workspace});const loginRoute=createRoute({getParentRoute:()=>rootRoute,path:'/login',validateSearch:(search:Record<string,unknown>)=>({redirect:typeof search.redirect==='string'?safeRedirect(search.redirect):'/'}),component:Login});const router=createRouter({routeTree:rootRoute.addChildren([indexRoute,loginRoute]),defaultPreload:'intent'});declare module '@tanstack/react-router'{interface Register{router:typeof router}}
const queryClient=createRueQueryClient();createRoot(document.getElementById('root')!).render(<StrictMode><ThemeProvider><KeynameProvider><QueryClientProvider client={queryClient}><RouterProvider router={router}/></QueryClientProvider></KeynameProvider></ThemeProvider></StrictMode>)
