import './styles.css'
import {StrictMode,useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {createRootRoute,createRoute,createRouter,Link,Outlet,RouterProvider,useNavigate} from '@tanstack/react-router'
import {QueryClientProvider,useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {useForm} from '@tanstack/react-form'
import {safeRedirect} from '@multiterm/rue-config/app'
import {createRueQueryClient} from '@multiterm/rue-trpc/client'
import {createRueClient,type RuePart,type RueSession} from '@multiterm/rue-sdk'
import {Badge,Button,ButtonLink,Card,CardContent,CardDescription,CardHeader,CardTitle,Input,ThemeControls,ThemeProvider} from '@multiterm/rue-ui'
import {app} from './app'
import {KeynameProvider,keynameAccessToken,useKeyname} from './auth'

const rue=createRueClient({baseUrl:app.urls.api,token:async()=>await keynameAccessToken()??undefined})
function KeyIcon(){return <svg aria-hidden="true" viewBox="0 0 24 24" className="size-4 fill-none stroke-current" strokeWidth="2"><circle cx="8" cy="15" r="4"/><path d="m11 12 8-8m-2 2 2 2m-5 1 2 2"/></svg>}
function Login(){const{status,user,error:authError,signIn}=useKeyname();const navigate=useNavigate();const{redirect}=loginRoute.useSearch();const[error,setError]=useState('');useEffect(()=>{if(status==='authenticated'&&user)void navigate({to:safeRedirect(redirect),replace:true})},[navigate,redirect,status,user]);const start=async(mode:'modal'|'redirect')=>{setError('');try{await signIn(mode)}catch(cause){setError(cause instanceof Error?cause.message:'Keyname sign-in failed')}};return <main className="grid min-h-dvh place-items-center px-5 py-12"><Card className="w-full max-w-md"><CardHeader className="text-center"><Link to="/" className="mx-auto mb-4 font-display text-3xl font-black text-primary">Rue</Link><CardTitle>Welcome back</CardTitle><CardDescription>Sign in with Keyname to continue to your Rue workspace.</CardDescription></CardHeader><CardContent className="grid gap-4"><Button size="lg" variant="secondary" className="w-full" isLoading={status==='loading'} disabled={status==='loading'} onClick={()=>void start('modal')}><KeyIcon/>Sign in with Keyname</Button><div className="flex items-center gap-3 text-xs font-semibold text-subtle"><span className="h-px flex-1 bg-border"/>OR<span className="h-px flex-1 bg-border"/></div><Button size="lg" variant="outline" className="w-full" onClick={()=>void start('redirect')}>Continue in a new page</Button>{(error||authError)&&<p role="alert" className="m-0 rounded-md border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error||authError}</p>}<p className="m-0 text-center text-xs leading-5 text-subtle">Keyname manages passwords, passkeys, connected providers, MFA, token refresh, and session revocation.</p></CardContent></Card></main>}

function partText(parts:RuePart[],messageId:string){return parts.filter((part)=>part.messageId===messageId&&part.type==='text'&&!part.payload.superseded).map((part)=>String(part.payload.text??'')).join('')}
function Workspace(){
  const auth=useKeyname();const navigate=useNavigate();const queryClient=useQueryClient();const[selectedId,setSelectedId]=useState<string>();const[notice,setNotice]=useState('')
  useEffect(()=>{if(auth.status==='anonymous'||auth.status==='error')void navigate({to:'/login',search:{redirect:'/'},replace:true})},[auth.status,navigate])
  const sessions=useQuery({queryKey:['sessions'],queryFn:()=>rue.sessions(),retry:false,enabled:auth.status==='authenticated'})
  useEffect(()=>{if(!selectedId&&sessions.data?.[0])setSelectedId(sessions.data[0].id)},[selectedId,sessions.data])
  const messages=useQuery({queryKey:['messages',selectedId],queryFn:()=>rue.messages(selectedId!),enabled:Boolean(selectedId),retry:false})
  const parts=useQuery({queryKey:['parts',selectedId],queryFn:()=>rue.parts(selectedId!),enabled:Boolean(selectedId),retry:false})
  const selected=useMemo(()=>sessions.data?.find((session)=>session.id===selectedId),[selectedId,sessions.data])
  const create=useMutation({mutationFn:()=>rue.createSession({title:'New session'}),onSuccess:async(session)=>{await queryClient.invalidateQueries({queryKey:['sessions']});setSelectedId(session.id);setNotice('New session ready.')}})
  const send=useMutation({mutationFn:async(text:string)=>{let id=selectedId;if(!id){const session=await rue.createSession({title:text.slice(0,60)});id=session.id;setSelectedId(id)}return rue.sendMessage(id,{text,wait:true})},onSuccess:async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:['sessions']}),queryClient.invalidateQueries({queryKey:['messages']}),queryClient.invalidateQueries({queryKey:['parts']})]);setNotice('Agent response completed.')},onError:(cause)=>setNotice(cause instanceof Error?cause.message:'Message failed')})
  const form=useForm({defaultValues:{message:''},onSubmit:async({value})=>{const text=value.message.trim();if(!text)return;form.reset();setNotice('Agent streaming…');await send.mutateAsync(text).catch(()=>undefined)}})
  if(auth.status==='loading')return <div role="status" className="grid min-h-dvh place-items-center text-sm text-muted">Checking your Keyname session…</div>
  return <main className="grid min-h-dvh grid-cols-[280px_1fr] max-md:grid-cols-1"><aside className="border-r border-border bg-background/60 p-6 backdrop-blur-xl max-md:hidden"><div className="font-display text-3xl font-black text-primary">Rue</div><Button className="mt-8 w-full" onClick={()=>create.mutate()} isLoading={create.isPending}>New session</Button><nav aria-label="Sessions" className="mt-8 grid gap-2 text-sm text-muted">{sessions.data?.map((session:RueSession)=><button className={`rounded-md px-3 py-2 text-left hover:bg-surface ${session.id===selectedId?'bg-surface text-foreground':''}`} key={session.id} onClick={()=>setSelectedId(session.id)}>{session.title||'Untitled session'}</button>)}{sessions.isError&&<span role="alert">Could not load sessions.</span>}{!sessions.isLoading&&!sessions.data?.length&&<span>No sessions yet</span>}</nav></aside><section className="grid min-w-0 grid-rows-[auto_1fr_auto] gap-5 p-6"><header className="flex items-center justify-between"><div><Badge>{auth.user?.userEmail??'Keyname session'}</Badge>{selected&&<h1 className="mt-2 text-xl font-bold">{selected.title||'Untitled session'}</h1>}</div><div className="flex items-center gap-3"><ButtonLink variant="ghost" href={app.urls.docs}>Docs</ButtonLink><ThemeControls/><Button variant="secondary" onClick={()=>void auth.signOut()}>Sign out</Button></div></header><article aria-label="Conversation" className="mx-auto flex w-full max-w-4xl flex-col gap-4 overflow-y-auto py-6">{!messages.data?.length?<div className="m-auto"><h2 className="font-display text-[clamp(3rem,7vw,6rem)] font-black leading-[.9] tracking-[-.05em]">One assistant.<br/><span className="text-primary">Every surface.</span></h2><p className="mt-6 text-lg text-muted">Start a session and ask Rue anything.</p></div>:messages.data.map((message)=><Card key={message.id} className={message.role==='user'?'ml-auto max-w-[80%]':'mr-auto max-w-[90%]'}><CardContent className="p-4"><p className="mb-2 text-xs font-bold uppercase text-subtle">{message.role}</p><div className="whitespace-pre-wrap">{partText(parts.data??[],message.id)||'…'}</div></CardContent></Card>)}{notice&&<p role="status" className="text-sm text-warning">{notice}</p>}</article><form onSubmit={(event)=>{event.preventDefault();event.stopPropagation();void form.handleSubmit()}} className="mx-auto flex w-full max-w-4xl gap-3"><form.Field name="message">{field=><Input aria-label="Message" placeholder="Ask Rue anything…" value={field.state.value} disabled={send.isPending} onChange={(event)=>field.handleChange(event.target.value)}/>}</form.Field><Button type="submit" isLoading={send.isPending}>Send</Button></form></section></main>
}
const rootRoute=createRootRoute({component:Outlet});const indexRoute=createRoute({getParentRoute:()=>rootRoute,path:'/',component:Workspace});const loginRoute=createRoute({getParentRoute:()=>rootRoute,path:'/login',validateSearch:(search:Record<string,unknown>)=>({redirect:typeof search.redirect==='string'?safeRedirect(search.redirect):'/'}),component:Login});const router=createRouter({routeTree:rootRoute.addChildren([indexRoute,loginRoute]),defaultPreload:'intent'});declare module '@tanstack/react-router'{interface Register{router:typeof router}}
const queryClient=createRueQueryClient();createRoot(document.getElementById('root')!).render(<StrictMode><ThemeProvider><KeynameProvider><QueryClientProvider client={queryClient}><RouterProvider router={router}/></QueryClientProvider></KeynameProvider></ThemeProvider></StrictMode>)
